name: read_snap
description: "ReadSnap is your personal reading companion. Track pages, time, and progress for all your books. Visualize your reading journey and stay motivated to hit your goals with effortless session logging and detailed statistics."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^3.1.0
  sqflite: ^2.4.2
  path: ^1.9.1
  uuid: ^4.5.1
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  google_fonts: ^6.3.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.9.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
